name: Deploy website (S3 + CloudFront)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: website-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # Install AWS CLI v2 (ensures 'aws' is available)
      - name: Install AWS CLI
        run: |
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Upload immutable assets first (long cache)
      - name: Sync assets (immutable)
        run: |
          aws s3 sync ./dist s3://$S3_BUCKET \
            --delete \
            --exclude index.html \
            --cache-control "public,max-age=31536000,immutable"
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      # Upload index.html with no-cache so content updates immediately
      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp ./dist/index.html s3://$S3_BUCKET/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
