name: Deploy website (S3 + CloudFront)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: website-deploy
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show basic info
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Repo root contents:"
          ls -la
          echo "Node/npm versions (before setup-node):"
          node -v || true
          npm -v || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show Node/npm after setup
        run: |
          node -v
          npm -v

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci
        # If your app is NOT at repo root, uncomment:
        # working-directory: ./<your-subfolder>

      - name: Build
        run: npm run build
        # working-directory: ./<your-subfolder>

      - name: List dist
        run: |
          echo "Dist contents:"
          ls -la dist || (echo "dist missing!" && exit 1)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync assets (immutable)
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-cli-command: >
            s3 sync ./dist s3://${{ secrets.S3_BUCKET }}
            --delete
            --exclude index.html
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html (no-cache)
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-cli-command: >
            s3 cp ./dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html
            --cache-control "no-cache, no-store, must-revalidate"
            --content-type "text/html"

      - name: Invalidate CloudFront
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-cli-command: >
            cloudfront create-invalidation
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            --paths "/*"
